version: 2

seeds:
  - name: Competitions_dim
    description: "Breakdown of competition start date and end date by year"
    columns:
      - name: Competition
        data-type: string

      - name: Year
        

      - name: start_date
        meta:
          dbt_utils:
            parse_dates: true

      - name: end_date
        meta:
          dbt_utils:
            parse_dates: true

models:
  - name: cleaned_appointments
    description: cleaned list of all appointments between 2023 and 2009
    columns:
      - name: primary_key
        tests:
          - unique
          - not_null
      - name: position
        test:
        - expected_values: ["Referee", "Assistant Referee", "Inspector/Assessor", "Fourth Official"]
      
